apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservationStatus
  labels:
    app: reservationStatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservationStatus
  template:
    metadata:
      labels:
        app: reservationStatus
    spec:
      containers:
        - name: reservationStatus
          image: username/reservationStatus:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5